In [ ]:
import warnings
import pandas as pd
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', 1000)
pd.set_option('display.max_rows', 1000)

In [ ]:
%matplotlib inline

from pathlib import Path
import numpy as np
import pandas as pd
import pandas_datareader.data as web
import gc
import statsmodels.api as sm
from statsmodels.regression.rolling import RollingOLS
from sklearn.preprocessing import scale
import talib
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

def plot_sharpe_ratio(path):
    """Plot Sharpe Ratio against Date from a given CSV file."""
    
    # Read the CSV file
    data = pd.read_csv(path, skiprows=1)
    
    # Split the single column into date and sharpe_ratio columns
    first_column_name = data.columns[0]  # get the name of the first column
    data['date'] = data[first_column_name].str.split().str[0]
    data['sharpe_ratio'] = data[first_column_name].str.split().str[1].astype(float)
    
    # Drop the original merged column
    data.drop(first_column_name, axis=1, inplace=True)
    
    # Set date as the index
    data.set_index('date', inplace=True)
    
    # Determine colors
    colors = ['blue' if val >= 0 else 'red' for val in data['sharpe_ratio']]
    
    # Plot
    plt.figure(figsize=(10, 5))
    data['sharpe_ratio'].plot(kind='bar', color=colors)
    plt.xlabel('Date')
    plt.ylabel('Sharpe Ratio')
    plt.title("Era Scores Over Time")
    plt.grid(axis='y')  # Show grid lines only on y-axis
    plt.tight_layout()
    plt.xticks(rotation=45)
    plt.show()

# Test the function
path = "/home/sayem/Desktop/Project/era_scores/YEAR_20130102_20141208_temp_era_scores.csv"
plot_sharpe_ratio(path)

In [ ]:
import os

def plot_all_files_in_directory(directory_path):
    """Iterate over all .csv files in the directory and plot Sharpe Ratio for each."""
    # List all files in the directory
    all_files = os.listdir(directory_path)

    # Filter only .csv files
    csv_files = [f for f in all_files if f.endswith('.csv')]

    # Iterate over each .csv file and plot the Sharpe Ratio
    for csv_file in csv_files:
        file_path = os.path.join(directory_path, csv_file)
        plot_sharpe_ratio(file_path)

# Specify the directory path
directory_path = "/home/sayem/Desktop/Project/era_scores"
plot_all_files_in_directory(directory_path)

In [ ]:
import pandas as pd
import numpy as np

# Sample tickers and dates
tickers = ['A', 'ZTS']
dates = pd.date_range('2001-01-02', '2017-12-29', freq='D')

# Create a MultiIndex
arrays = [np.array(tickers).repeat(len(dates)), np.tile(dates, len(tickers))]
multi_index = pd.MultiIndex.from_arrays(arrays, names=('Ticker', 'Date'))

# Create dummy data for columns
num_entries = len(tickers) * len(dates)
dummy_data = np.random.rand(num_entries, 225).astype(np.float32)

# Column names based on your example
columns = [f"{str(i).zfill(2)}_DUMMY" for i in range(1, 226)]

# Create the DataFrame
df_dummy = pd.DataFrame(dummy_data, index=multi_index, columns=columns)

df_dummy.shape

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Generate dummy data
tickers = ['A', 'B']
dates = pd.date_range('2022-01-01', '2022-01-10', freq='D')
arrays = [np.array(tickers).repeat(len(dates)), np.tile(dates, len(tickers))]
multi_index = pd.MultiIndex.from_arrays(arrays, names=('Ticker', 'Date'))
dummy_data = np.random.rand(len(tickers) * len(dates), 225).astype(np.float32)
df_dummy = pd.DataFrame(dummy_data, index=multi_index)

In [ ]:
df_dummy

In [ ]:
def visualize_data_as_image(df, ticker):
    # Reshape the data into 15x15 grayscale images
    images = df.loc[ticker].values.reshape(-1, 15, 15)
    
    # Stack images vertically to form a strip
    image_strip = np.vstack(images)
    
    # Plot
    plt.imshow(image_strip, cmap='gray')
    plt.title(f"Data for {ticker} as Grayscale Image Strip")
    plt.xlabel("Features reshaped to 15x15")
    plt.ylabel("Days")
    plt.colorbar(label="Feature Value")
    plt.show()

# Visualize for ticker 'A'
visualize_data_as_image(df_dummy, 'A')

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Generating the same dummy data from before
tickers = ['A', 'B']
dates = pd.date_range('2022-01-01', '2022-01-10', freq='D')
arrays = [np.array(tickers).repeat(len(dates)), np.tile(dates, len(tickers))]
multi_index = pd.MultiIndex.from_arrays(arrays, names=('Ticker', 'Date'))
dummy_data = np.random.rand(len(tickers) * len(dates), 225).astype(np.float32)
df_dummy = pd.DataFrame(dummy_data, index=multi_index)

def visualize_data_for_one_day(df, ticker, date):
    # Extract the data for the specified ticker and date
    day_data = df.loc[(ticker, date)]
    
    # Reshape the data into a 15x15 grayscale image
    image = day_data.values.reshape(15, 15)
    
    # Plot
    plt.imshow(image, cmap='gray')
    plt.title(f"Data for {ticker} on {date}")
    plt.colorbar(label="Feature Value")
    plt.show()

# Visualize for ticker 'A' for the first day
visualize_data_for_one_day(df_dummy, 'A', '2022-01-01')

In [9]:
import pandas as pd
import numpy as np

# Sample tickers and dates
tickers = ['A', 'ZTS']
dates = pd.date_range('2001-01-02', '2001-01-04', freq='D')

# Create a MultiIndex
arrays = [np.tile(dates, len(tickers)), np.array(tickers).repeat(len(dates))]
multi_index = pd.MultiIndex.from_arrays(arrays, names=('Date', 'Ticker'))

# Create dummy data for columns
num_entries = len(tickers) * len(dates)
dummy_data = np.random.rand(num_entries, 10).astype(np.float32)

# Column names
columns = [f"col_{i}" for i in range(10)]

# Create the DataFrame
df_dummy = pd.DataFrame(dummy_data, index=multi_index, columns=columns)

df_dummy

,,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9
Date,Ticker,,,,,,,,,,
2001-01-02,A,0.953445,0.546494,0.203197,0.487987,0.802021,0.634905,0.874461,0.484120,0.812850,0.578882
2001-01-03,A,0.421677,0.469277,0.887161,0.876576,0.709585,0.408407,0.072912,0.116620,0.362657,0.642377
2001-01-04,A,0.375267,0.667692,0.796484,0.072245,0.622691,0.623865,0.640922,0.627993,0.631215,0.304100
2001-01-02,ZTS,0.365955,0.782734,0.358986,0.482563,0.217692,0.394863,0.224153,0.436102,0.635085,0.438742
2001-01-03,ZTS,0.629698,0.752522,0.610183,0.376268,0.147213,0.591908,0.210040,0.031302,0.728297,0.731139
2001-01-04,ZTS,0.060799,0.763103,0.046731,0.939997,0.448219,0.141806,0.764570,0.223903,0.661133,0.050715

In [14]:
import pandas as pd
import numpy as np

# Sample tickers and dates
tickers = ['AAPL', 'GOOGL']
dates = pd.date_range('2013-01-02', '2013-01-04', freq='D')

# Create a MultiIndex
arrays = [np.tile(tickers, len(dates)), np.repeat(dates, len(tickers))]
multi_index = pd.MultiIndex.from_arrays(arrays, names=('Ticker', 'Date'))

# Create dummy data for columns
num_entries = len(tickers) * len(dates)
dummy_data = {
    'open': np.random.rand(num_entries),
    'high': np.random.rand(num_entries),
    'low': np.random.rand(num_entries),
    'close': np.random.rand(num_entries),
    'volume': np.random.rand(num_entries) * 1e6,
    'market cap': np.random.rand(num_entries) * 1e12,
    'sector': np.random.choice([0.0, 1.0, 2.0, 3.0], size=num_entries),
    'ret_frac_order': np.random.rand(num_entries) * 100
}

# Create the DataFrame
df_dummy = pd.DataFrame(dummy_data, index=multi_index)

df_dummy

,,open,high,low,close,volume,market cap,sector,ret_frac_order
Ticker,Date,,,,,,,,
AAPL,2013-01-02,0.479513,0.417990,0.986555,0.635973,53690.212113,9.275609e+11,2.0,86.515753
GOOGL,2013-01-02,0.100202,0.173959,0.236644,0.181368,182048.823192,7.364189e+09,1.0,84.335484
AAPL,2013-01-03,0.789291,0.549934,0.632761,0.729403,35410.328610,6.904751e+11,0.0,47.698246
GOOGL,2013-01-03,0.923715,0.050574,0.206033,0.919569,132208.427726,6.207232e+10,0.0,67.842536
AAPL,2013-01-04,0.076655,0.852655,0.930951,0.074803,479784.337865,1.933185e+11,0.0,55.079054
GOOGL,2013-01-04,0.077715,0.400038,0.508555,0.868796,979751.895952,2.319937e+11,1.0,65.731294

In [15]:
import pandas as pd
import numpy as np

# Sample tickers and dates
tickers = ['AAPL', 'GOOGL']
dates = pd.date_range('2013-01-02', '2013-01-04', freq='D')

# Create a MultiIndex: this time, we'll use repeat for the dates and tile for the tickers to get the desired arrangement
arrays = [np.repeat(dates, len(tickers)), np.tile(tickers, len(dates))]
multi_index = pd.MultiIndex.from_arrays(arrays, names=('Date', 'Ticker'))

# Create dummy data for columns
num_entries = len(tickers) * len(dates)
dummy_data = {
    'open': np.random.rand(num_entries),
    'high': np.random.rand(num_entries),
    'low': np.random.rand(num_entries),
    'close': np.random.rand(num_entries),
    'volume': np.random.rand(num_entries) * 1e6,
    'market cap': np.random.rand(num_entries) * 1e12,
    'sector': np.random.choice([0.0, 1.0, 2.0, 3.0], size=num_entries),
    'ret_frac_order': np.random.rand(num_entries) * 100
}

# Create the DataFrame
df_dummy = pd.DataFrame(dummy_data, index=multi_index)

df_dummy

                       open      high       low     close         volume  \
Date       Ticker
2013-01-02 AAPL    0.986300  0.557872  0.689783  0.999959  734513.723530
           GOOGL   0.172606  0.919063  0.060492  0.980354   40948.480272
2013-01-03 AAPL    0.330226  0.696161  0.551477  0.752125  386838.791849
           GOOGL   0.056897  0.956120  0.270145  0.399170  745069.801189
2013-01-04 AAPL    0.088824  0.513403  0.250122  0.330707   89234.245812
           GOOGL   0.891983  0.573485  0.938676  0.038720   89504.657708

                     market cap  sector  ret_frac_order
Date       Ticker
2013-01-02 AAPL    6.817249e+11     0.0       61.671446
           GOOGL   3.205930e+11     2.0       10.807085
2013-01-03 AAPL    7.278992e+11     1.0       61.301583
           GOOGL   3.245248e+11     2.0       65.069677
2013-01-04 AAPL    4.291848e+10     1.0        2.073928
           GOOGL   5.957642e+09     3.0       77.357902